apiVersion: accesscontextmanager.gcp.upbound.io/v1beta1
kind: ServicePerimeterResource
metadata:
  annotations:
    meta.upbound.io/example-id: accesscontextmanager/v1beta1/serviceperimeterresource
  labels:
    testing.upbound.io/example-name: service-perimeter-resource
  name: service-perimeter-resource
spec:
  forProvider:
    perimeterName: ${google_access_context_manager_service_perimeter.service-perimeter-resource.name}
    resource: projects/987654321

---

