apiVersion: gcp.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
spec:
  projectID: official-provider-testing
  credentials:
    source: Secret
    secretRef:
      name: provider-creds
      namespace: upbound-system
      key: creds
