apiVersion: bigtable.gcp.upbound.io/v1beta1
kind: TableIAMMember
metadata:
  annotations:
    meta.upbound.io/example-id: bigtable/v1beta1/tableiammember
  labels:
    testing.upbound.io/example-name: editor
  name: editor
spec:
  forProvider:
    instance: instance
    role: roles/bigtable.user
    table: table
    member: serviceAccount:${data.google_iam_member.member}

---

apiVersion: bigtable.gcp.upbound.io/v1beta1
kind: Table
metadata:
  annotations:
    meta.upbound.io/example-id: bigtable/v1beta1/tableiammember
  labels:
    testing.upbound.io/example-name: table
  name: table
spec:
  forProvider:
    instanceNameSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    splitKeys:
      - a
      - b
      - c

---

apiVersion: bigtable.gcp.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: bigtable/v1beta1/tableiammember
  labels:
    testing.upbound.io/example-name: instance
  name: instance
spec:
  forProvider:
    cluster:
      - clusterId: tf-instance-cluster
        numNodes: 3
        storageType: HDD
        zone: us-central1-b
    deletionProtection: false
