apiVersion: alloydb.gcp.upbound.io/v1beta1
kind: Cluster
metadata:
  annotations:
    meta.upbound.io/example-id: alloydb/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    location: us-central1
    network: projects/${data.google_project.project.number}/global/networks/${google_compute_network.default.name}

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: Network
metadata:
  annotations:
    meta.upbound.io/example-id: alloydb/v1beta1/cluster
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider: {}
