apiVersion: logging.gcp.upbound.io/v1beta1
kind: FolderBucketConfig
metadata:
  annotations:
    meta.upbound.io/example-id: logging/v1beta1/folderbucketconfig
    upjet.upbound.io/manual-intervention: "FolderBucketConfig requires a folder id"
  labels:
    testing.upbound.io/example-name: basic
  name: basic
spec:
  forProvider:
    bucketId: _Default
    folderSelector:
      matchLabels:
        testing.upbound.io/example-name: default
    location: global
    retentionDays: 30

---
apiVersion: cloudplatform.gcp.upbound.io/v1beta1
kind: Folder
metadata:
  annotations:
    meta.upbound.io/example-id: logging/v1beta1/folderbucketconfig
    upjet.upbound.io/manual-intervention: "Requires organization level IAM permissions"
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    displayName: some-folder-name
    parentSelector:
      matchLabels:
        testing.upbound.io/example-name: example
