apiVersion: osconfig.gcp.upbound.io/v1beta1
kind: OsPolicyAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: osconfig/v1beta1/ospolicyassignment
  labels:
    testing.upbound.io/example-name: primary
  name: primary
spec:
  forProvider:
    description: A test os policy assignment
    instanceFilter:
    - all: false
      exclusionLabels:
      - labels:
          label-two: value-two
      inclusionLabels:
      - labels:
          label-one: value-one
      inventories:
      - osShortName: centos
        osVersion: 8.*
    location: us-west1-a
    osPolicies:
    - allowNoResourceGroupMatch: false
      description: A test os policy
      id: policy
      mode: VALIDATION
      resourceGroups:
      - inventoryFilters:
        - osShortName: centos
          osVersion: 8.*
        resources:
        - id: apt
          pkg:
          - apt:
            - name: bazel
            desiredState: INSTALLED
    project: my-project-name
    rollout:
    - disruptionBudget:
      - fixed: 1
      minWaitDuration: 3.5s
