---
apiVersion: accesscontextmanager.gcp.upbound.io/v1beta1
kind: AccessLevel
metadata:
  annotations:
    meta.upbound.io/example-id: accesscontextmanager/v1beta1/accesslevel
    upjet.upbound.io/manual-intervention: "Requires organization level IAM permissions"
  labels:
    testing.upbound.io/example-name: access-level
  name: access-level
spec:
  forProvider:
    basic:
    - conditions:
      - devicePolicy:
        - osConstraints:
          - osType: DESKTOP_CHROME_OS
          requireScreenLock: true
        regions:
        - CH
        - IT
        - US
    name: accessPolicies/${google_access_context_manager_access_policy.access-policy.name}/accessLevels/chromeos_no_lock
    parentSelector:
      matchLabels:
        testing.upbound.io/example-name: access-policy
    title: chromeos_no_lock

---

apiVersion: accesscontextmanager.gcp.upbound.io/v1beta1
kind: AccessPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: accesscontextmanager/v1beta1/accesslevel
    upjet.upbound.io/manual-intervention: "Requires organization level IAM permissions"
  labels:
    testing.upbound.io/example-name: access-policy
  name: access-policy
spec:
  forProvider:
    parent: organizations/123456789
    title: my policy
