apiVersion: certificatemanager.gcp.upbound.io/v1beta1
kind: DNSAuthorization
metadata:
  annotations:
    meta.upbound.io/example-id: certificatemanager/v1beta1/dnsauthorization
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    location: global
    description: The default dnss
    domain: hashicorptest.com
