# SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: compute.gcp.upbound.io/v1beta2
kind: InstanceTemplate
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta2/instancetemplate
  labels:
    testing.upbound.io/example-name: instance-template
  name: instance-template
spec:
  forProvider:
    canIpForward: false
    description: This template is used to create app server instances.
    disk:
    - autoDelete: false
      boot: true
      sourceImage: debian-cloud/debian-11
    instanceDescription: Description assigned to instances
    labels:
      environment: dev
    machineType: e2-medium
    metadata:
      environment: dev
    networkInterface:
    - network: default
    scheduling:
      automaticRestart: true
      onHostMaintenance: MIGRATE
    tags:
    - foo
    - bar
