apiVersion: compute.gcp.upbound.io/v1beta1
kind: FirewallPolicyRule
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/firewallpolicyrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    action: allow
    description: Example Resource
    direction: EGRESS
    disabled: false
    enableLogging: true
    firewallPolicySelector:
      matchLabels:
        testing.upbound.io/example-name: default
    match:
    - destIpRanges:
      - 11.100.0.1/32
      layer4Configs:
      - ipProtocol: tcp
        ports:
        - 80
        - 8080
    priority: 9000

---

apiVersion: compute.gcp.upbound.io/v1beta1
kind: FirewallPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/firewallpolicyrule
  labels:
    testing.upbound.io/example-name: default
  name: default
spec:
  forProvider:
    description: Example Resource
    parent: organizations/12345
    shortName: my-policy
