apiVersion: meta.pkg.crossplane.io/v1alpha1
kind: Provider
metadata:
  name: provider-gcp-{{ APIGROUP }}
  labels:
    pkg.crossplane.io/provider-family: gcp
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/provider-gcp
    meta.crossplane.io/description: |
      Upbound's official Crossplane provider to manage Google Cloud Platform (GCP)
      {{ APIGROUP }} services in Kubernetes.
    meta.crossplane.io/readme: |
      Provider GCP is a Crossplane provider for [Google Cloud Platform
      (GCP)](https://cloud.google.com) developed and supported by Upbound.
      Available resources and their fields can be found in the [Upbound
      Marketplace](https://marketplace.upbound.io/providers/upbound/provider-gcp).
      If you encounter an issue please reach out on support@upbound.io email
      address. This is a subpackage for the {{ APIGROUP }} API group.
    friendly-name.meta.crossplane.io: Provider GCP ({{ APIGROUP }})
spec:
  dependsOn:
    - provider: {{ XPKG_REG_ORGS }}/provider-gcp-config
      version: "{{ DEP_CONSTRAINT }}"
