name: Updoc

on:
  workflow_dispatch:
    inputs:
      subpackages:
        description: "Subpackages to be published individually (e.g. monolith config ec2)"
        default: "monolith"
        required: false

jobs:
  publish-docs:
    uses: upbound/uptest/.github/workflows/provider-updoc.yml@main
    with:
      subpackages: ${{ github.event.inputs.subpackages }}
    secrets:
      UPBOUND_CI_PROD_BUCKET_SA: ${{ secrets.UPBOUND_CI_PROD_BUCKET_SA }}
